# Generated by Django 5.1.3 on 2024-11-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('thumbnail', models.ImageField(null=True, upload_to='main')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('logo', models.ImageField(null=True, upload_to='main')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
